name: Pruebadoit
favicon: null
layout_spectrum: 0.8228137225378305
typography_spectrum: 0.12945764139294624
title: Star Service
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3102386109530926
  lightness: 0.41834755684249103
  saturation: 0.6647005213890225
  rhythmicContrast: 0.4417256466113031
purpose: []
